### ISSUE TITLE
Wav encoding error

### ISSUE THREAD

**Issue by oneofthehorses** [mihai-bontea/StegEncoder#1]
Hello! 
Thanks for your work! 
Have problem with encoding .wav file
P.S. Hope to see video encoding too!

![image](https://github.com/mihai-bontea/StegEncoder/assets/151937835/5d71afed-6c0a-4ce8-8a23-a7061310e245)

**Comment by mihai-bontea** [comment]
I removed this limitation, it should now allow higher bit-depths as well.
